name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npm install

    - name: Build React App
      run: |
        npm run build

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          # Backend deployment
          cd /var/www/ozguruzden.com
          git pull origin main
          npm install

          # Frontend deployment
          cd /var/www/ozguruzden.com
          rm -rf build
          mkdir -p build


            echo "NODE_ENV=production" > .env
          echo "PORT=443" >> .env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
          
          # PM2 ile yeniden başlat
          pm2 restart ozguruzden-server