name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Node.js versiyonunu 20'ye yükselttik

    - name: Check directory structure
      run: |
        pwd
        ls -la

    - name: Install Dependencies
      run: |
        npm install --legacy-peer-deps # Uyumluluk sorunlarını görmezden gelmek için

    - name: Build React App
      run: |
        npm run build # personal-page dizinine gitmeye gerek yok

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/ozguruzden.com
          git pull origin main
          npm install --legacy-peer-deps
          npm run build
          pm2 restart ozguruzden-server
