name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        npm install --save-dev @babel/plugin-proposal-private-property-in-object
        npm install --legacy-peer-deps

    - name: Build React App
      env:
        CI: false  # Warning'leri error olarak değerlendirmeyi kapat
      run: |
        npm run build

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/ozguruzden.com
          git pull origin main
          npm install --legacy-peer-deps
          export CI=false && npm run build
          pm2 restart ozguruzden-server